

import type { Metadata } from "next";
import HeaderDashboard from "@/components/Header/headerDashboard";



export const metadata: Metadata = {
  title: "Discount App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
   <>
   <HeaderDashboard/>
   </>
  )
}
