
export const BASE_URL_API = process.env.NEXT_PUBLIC_API
export const BASE_URL_BUSINESS_OWNER = process.env.NEXT_PUBLIC_BUSINESS_OWNER_API
export const BASE_URL_USERS = process.env.NEXT_PUBLIC_USERS_API
export const BASE_URL_ROLL = process.env.NEXT_PUBLIC_ROLL_API 
export const BASE_URL_SEARCH_INFORMATION = process.env.NEXT_PUBLIC_SEARCH_INFORMATION
export const BASE_URL_BUSINESS_OWNER_INFO_SEARCHED = process.env.NEXT_PUBLIC_GET_BUSINESSOWNER_INFOS_SEARCHED
export const BASE_URL_REPORTS = process.env.NEXT_PUBLIC_REPORTS
export const BASE_URL_ADMIN = process.env.NEXT_PUBLIC_ADMIN
