import "../globals.css";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import { AuthContextProvider } from "@/context/authContext";
import ReactQueryProvider from "@/components/clients/providers/reactQueryProvider";
import HomePageHeader from "@/components/Header/homePageHeader";
import ToastifyContainer from "@/components/clients/providers/toastifyContainer";

export const metadata: Metadata = {
  title: "EyeRoll account",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden min-h-screen h-max inset-0 w-screen bg-sky-100">
        <AuthContextProvider>
          <ReactQueryProvider>
            <HomePageHeader />
            {children}
            <ToastifyContainer />
          </ReactQueryProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
